on:
  workflow_dispatch:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test conda skeleton publish action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish conda package from PyPI package
        uses: ./
        with:
          pypi_package: "driptorch"
          package_version: "0.4.1"
          python_version: "3.10"
          upload_channel: "holtz"
          access_token: ${{ secrets.ANACONDA_TOKEN }}
          stable: true
